### PR TITLE
Fix lower

### PR DESCRIPTION
**Pull request by lsmith77**
fixes https://github.com/symfony-cmf/MenuBundle/issues/228

### CODE REVIEW

**Comment by lsmith77** [comment]
there seem to be an issue with route loading https://travis-ci.org/symfony-cmf/MenuBundle/jobs/71482167#L265

**Comment by WouterJ** [comment]
Huh, did Composer suddently changes the behaviour of `1.12.0` (instead of requiring the stable version, it falls back to `1.12-dev`?). If so, I think it should be fixed on Composer's side /cc @Seldaek

**Comment by Seldaek** [comment]
Your --prefer-lowest build probably needs a --prefer-stable as well.

**Comment by dbu** [comment]
we had that discussion before: imho we want to be sure our lowest requirements are true without the --prefer-stable flag. will have a look what needs to be upped.

**Comment by WouterJ** [comment]
Please also note that this worked perfectly a couple of days ago without the `--prefer-stable` flag.

**Comment by dbu** [comment]
looks like knp released 2.0.0 of the lib and bundle \o/
and seems they did some last BC breaks since the alpha. now seems to work. lets see if travis agrees. squash and merge?

**Pull request merged**
