### PR TITLE
prevent exceptions on menu names that are not valid node names

### PR DESCRIPTION
**Pull request by dbu**
fix #223
cc @ahmadrabie 

once merged, we also need to merge 1.2 into master to fix version 2

### CODE REVIEW

**Comment by dbu** [comment]
oh well. will look at the test failure later today...

**Comment by dbu** [comment]
ok, the test should be green now. i am unsure if we should still add a try-catch as there could be implementation specific limitations on node names that are not covered the the phpcr-utils helper. but this certainly is better than no tests at all.

**Comment by dbu** [comment]
@lsmith77 can you please have a look at this?

**Comment by lsmith77** [comment]
makes sense to me .. maybe there should be a method in PHPCR to validate a path name

**Comment by WouterJ** [comment]
:+1:

**Comment by dbu** [comment]
the method is a bit tricky. to be strict, the implementation would have to provide the validator. what exactly valid paths are is up to the implementation.

we could try to do the request and catch exceptions, but this is often just the RepositoryException, which could hide issues with the repository and make debugging harder.

**Comment by dbu** [comment]
shall we go with this or try something more fancy? i restarted the builds where composer ran out of memory...

**Comment by lsmith77** [comment]
fixed the tests .. good to merge I guess.

**Pull request merged**
